services:
  api:
    image: codex-api:amd64
    restart: unless-stopped
    networks:
      - codex-network
    expose:
      - 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: vip

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - codex-network

networks:
  codex-network:
    name: codex-network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
