services:
  api:
    image: codex-api:amd64
    container_name: codex-api
    restart: unless-stopped
    networks:
      - codex-network
    expose:
      - 8080

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - codex-network

networks:
  codex-network:
    name: codex-network
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
